WIP: Use jvm.options like ES

diff --git a/bin/system-install b/bin/system-install
--- a/bin/system-install
+++ b/bin/system-install
@@ -6,8 +6,8 @@ setup
 
 name=logstash
 
-[ -r /etc/default/$name ] && . /etc/default/$name
-[ -r /etc/sysconfig/$name ] && . /etc/sysconfig/$name
+[ -r ${LOGSTASH_HOME}/config/settings ] && . ${LOGSTASH_HOME}/config/settings
+[ -r /etc/logstash/settings ] && . /etc/logstash/settings
 
 # bin/logstash-plugin is a short lived ruby script thus we can use aggressive "faster starting JRuby options"
 # see https://github.com/jruby/jruby/wiki/Improving-startup-time
@@ -18,8 +18,8 @@ tempfile=$(mktemp)
 
 read -r -d '' PRESTART << EOM
 # Load the defaults
-[ -r /etc/default/$name ] && . /etc/default/$name
-[ -r /etc/sysconfig/$name ] && . /etc/sysconfig/$name
+[ -r ${LOGSTASH_HOME}/config/settings ] && . ${LOGSTASH_HOME}/config/settings
+[ -r /etc/logstash/settings ] && . /etc/logstash/settings
 
 /bin/touch ${LS_LOG_FILE}
 EOM
@@ -43,23 +43,23 @@ if [ $exit_code -ne 0 ]; then
   cat $tempfile
   echo "Unable to install system startup script for Logstash."
 else
-  if [ -f "/lib/systemd/system/logstash.service" ]; then
-    if [ ! -f "/etc/default/logstash" ]; then
-      sed -i -e 's|EnvironmentFile=/etc/default/logstash|#EnvironmentFile=/etc/default/logstash|' /lib/systemd/system/logstash.service
-    fi
-    if [ ! -f "/etc/sysconfig/logstash" ]; then
-      sed -i -e 's|EnvironmentFile=/etc/sysconfig/logstash|#EnvironmentFile=/etc/sysconfig/logstash|' /lib/systemd/system/logstash.service
-    fi
-    systemctl --system daemon-reload
-    ec=$?
-    if [ $ec -ne 0 ]; then
-      echo "'systemctl --system daemon-reload' failed. Check the output of 'systemctl status logstash.service'"
-    else
-      echo "Successfully created system startup script for Logstash"
-      rm $tempfile
-      exit 0
-    fi
-  fi
+  # if [ -f "/lib/systemd/system/logstash.service" ]; then
+  #   if [ ! -f "/etc/default/logstash" ]; then
+  #     sed -i -e 's|EnvironmentFile=/etc/default/logstash|#EnvironmentFile=/etc/default/logstash|' /lib/systemd/system/logstash.service
+  #   fi
+  #   if [ ! -f "/etc/sysconfig/logstash" ]; then
+  #     sed -i -e 's|EnvironmentFile=/etc/sysconfig/logstash|#EnvironmentFile=/etc/sysconfig/logstash|' /lib/systemd/system/logstash.service
+  #   fi
+  #   systemctl --system daemon-reload
+  #   ec=$?
+  #   if [ $ec -ne 0 ]; then
+  #     echo "'systemctl --system daemon-reload' failed. Check the output of 'systemctl status logstash.service'"
+  #   else
+  #     echo "Successfully created system startup script for Logstash"
+  #     rm $tempfile
+  #     exit 0
+  #   fi
+  # fi
   echo "Successfully created system startup script for Logstash"
 fi
 rm $tempfile
